Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcStok.Models.Entity;

namespace mvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri

        mvcDbStokEntities db = new mvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler =from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(a => a.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());

            //var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult SIL(int id) 
        {
            var sil = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(sil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var mst = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir",mst);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var mst = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            mst.MUSTERIAD = p1.MUSTERIAD;
            mst.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Musteri/Index.cshtml
@using mvcStok.Models.Entity;
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
{
    <div>
        <p>Aranacak Müşteri Adı : @Html.TextBox("p") </p>
        <input type="submit" value="Ara" class="btn btn-outline-primary" />
    </div>
    


    <br />
    <br />

}
<table class="table table-bordered">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Alert</th>

    </tr>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MUSTERIID</td>
                <td>@item.MUSTERIAD</td>
                <td>@item.MUSTERISOYAD</td>

                <td><a href="/MUSTERI/SIL/@item.MUSTERIID" class="btn btn-danger">Sil</a></td>
                <td><a href="/MUSTERI/MusteriGetir/@item.MUSTERIID" class="btn btn-success">Güncelle</a></td>
                <td>@Html.ActionLink("SİL BUTONU", "SIL", new { id = @item.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten silmek istiyormusunuz ?')" }) </td>

            </tr>
        }
    </tbody>
</table>
<a href="/MUSTERI/YeniMusteri/" class="btn btn-primary">Yenim Müşteri Ekle</a>

Views/Musteri/MusteriGetir.cshtml
@model mvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(a => a.MUSTERIID)
        @Html.TextBoxFor(a => a.MUSTERIID, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.MUSTERIAD)
        @Html.TextBoxFor(a => a.MUSTERIAD, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.MUSTERISOYAD)
        @Html.TextBoxFor(a => a.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>
}

Views/Musteri/YeniMusteri.cshtml
@model mvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*<div>
        <label>Müşteri Adı</label>
        <input type="text" class="form-control" name="MUSTERIAD" />
    </div>*@

    <div>
        <label>Müşteri Adı</label>
        @Html.TextAreaFor(a => a.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.MUSTERIAD, "", new { @style = "color:gray" })
    </div>
    <br>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <br />
    <div>
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı');

        });
    </script>
</form>