Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcStok.Models.Entity;

namespace mvcStok.Controllers
{
    public class UrunController : Controller
    {

        mvcDbStokEntities db = new mvcDbStokEntities();
        
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList() 
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m=>m.KATEGORIID==p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg; 
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SIL(int id)
        {
          var urun =  db.TBLURUNLER.Find(id);
          db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            
            return View("UrunGetir",urun);
        }
        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;
            //urun.URUNKATEGORI = p.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Urun/Index.cshtml
@using mvcStok.Models.Entity;
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>Ürün ID</th>
            <th>Ürün Adı</th>
            <th>Markası</th>
            <th>Kategori</th>
            <th>Fiyat</th>
            <th>Stok</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.URUNID</td>
                <td>@item.URUNAD</td>
                <td>@item.MARKA</td>
                <td>@item.TBLKATEGORILER.KATEGORIAD</td>
                <td>@item.FIYAT</td>
                <td>@item.STOK</td>
                <td><a href="/URUN/SIL/@item.URUNID" class="btn btn-danger">Sil</a></td>
                <td><a href="/URUN/UrunGetir/@item.URUNID" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>

<a href="/URUN/UrunEkle/" class="btn btn-primary">Yeni Ürün Ekle</a>


<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />

@*<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />*@
@*<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />*@
<script>
    $('#tbl1').DataTable();
</script>

Views/Urun/UrunEkle.cshtml
@model mvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="URUNAD"  required="" maxlength="50"/> 
    </div>
    <br>
    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="MARKA" required="" placeholder="Buraya Markayı Yazınız"/>
    </div>
    <br />
    <div>
        <label>Kategori Seçiniz</label>
        @Html.DropDownListFor(x =>x.TBLKATEGORILER.KATEGORIID ,(List<SelectListItem>)ViewBag.dgr, new {@class="form-control" })
    </div>
    <br />
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="FIYAT"  required=""/>
    </div>
    <br />
    <div>
        <label>Stok Adet</label>
        <input type="text" class="form-control" name="STOK" required="" />
    </div>
    <br />
















    <div>
        <button class="btn btn-info">Ürün Ekle</button>
    </div>
</form>

Views/Urun/UrunGetir.cshtml
@model mvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(a => a.URUNID)
        @Html.TextBoxFor(a => a.URUNID, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.URUNAD)
        @Html.TextBoxFor(a => a.URUNAD, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.MARKA)
        @Html.TextBoxFor(a => a.MARKA, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.URUNKATEGORI)
        @Html.DropDownListFor(a => a.TBLKATEGORILER.KATEGORIID, (List< SelectListItem >)ViewBag.dgr, new { @class = "form-control" })
        @*@Html.TextBoxFor(a => a.URUNKATEGORI, new { @class = "form-control" })*@
        <br>
        @Html.LabelFor(a => a.FIYAT)
        @Html.TextBoxFor(a => a.FIYAT, new { @class = "form-control" })
        <br>
        @Html.LabelFor(a => a.STOK)
        @Html.TextBoxFor(a => a.STOK, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Ürün Güncelle</button>
    </div>
}