Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace mvcStok.Controllers
{
    public class KategoriController : Controller
    {
        mvcDbStokEntities db = new mvcDbStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            //var degerler = db.TBLKATEGORILER.ToList();
            var degerler = db.TBLKATEGORILER.ToList().ToPagedList(sayfa,10);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniKategori() 
        {
            return View();
        }

        [HttpPost] 
        public ActionResult YeniKategori(TBLKATEGORILER p1) 
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }
            db.TBLKATEGORILER.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult SIL(int id) 
        {
            var kategori = db.TBLKATEGORILER.Find(id);
            db.TBLKATEGORILER.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TBLKATEGORILER.Find(id);
            return View ("KategoriGetir",ktgr);
        }

        public ActionResult Guncelle(TBLKATEGORILER p1)
        {
            var ktgr = db.TBLKATEGORILER.Find(p1.KATEGORIID);
            ktgr.KATEGORIAD = p1.KATEGORIAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Kategori/Index.cshtml
@using mvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLKATEGORILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Kategori ID</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.KATEGORIID</td>
                <td>@item.KATEGORIAD</td>
                <td><a href="/Kategori/SIL/@item.KATEGORIID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Kategori/KategoriGetir/@item.KATEGORIID" class="btn btn-success">Güncelle</a></td>
                
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index",new {sayfa}))

<a href="/KATEGORI/YeniKategori/" class="btn btn-primary">Yeni Kategori</a>

Views/Kategori/KategoriGetir.cshtml
@model mvcStok.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle","Kategori",FormMethod.Post))
            {
                <div class="form-group">

                    @Html.LabelFor(a=>a.KATEGORIID)
                    @Html.TextBoxFor(a => a.KATEGORIID, new {@class = "form-control"})
                    <br>
                    @Html.LabelFor(a=>a.KATEGORIAD)
                    @Html.TextBoxFor(a=> a.KATEGORIAD, new {@class = "form-control"})
                </div>
                <div>
                    <button class="btn btn-warning">Kategori Güncelle</button>
                </div>
            }

Views/Kategori/YeniKategori.cshtml
@model mvcStok.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*<div>
        <label>Kategori Adı</label>
        <input type="text" class="form-control" name="KATEGORIAD" />
    </div>*@


    <div>
        <label>Kategori Adı</label>
        @Html.TextAreaFor(a=>a.KATEGORIAD, new {@class = "form-control"})
        @Html.ValidationMessageFor(a => a.KATEGORIAD, "", new {@style = "color:blue"})
    </div>


    <br />
    <div>
        <button class="btn btn-info">Kategori Ekle</button>
    </div>
</form>